services:
  # 1. Database Service
  database:
    image: postgis/postgis:15-3.3
    container_name: coopflow_db
    environment:
      POSTGRES_DB: coopflow_db
      POSTGRES_USER: coopflow_user
      POSTGRES_PASSWORD: secretpassword
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  # 2. Backend Service
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: coopflow_backend
    volumes:
      - ./backend:/var/www
    depends_on:
      - database

  # 3. Web Server Service
  webserver:
    image: nginx:alpine
    container_name: coopflow_webserver
    ports:
      - "8000:80"
    volumes:
      - ./backend:/var/www
      - ./backend/docker/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend

  # 4. ML Engine Service (PASTIKAN SEJAJAR DENGAN WEBSERVER, BACKEND, DATABASE)
  ml-engine:
    build:
      context: ./ml-engine
      dockerfile: Dockerfile
    container_name: coopflow_ml
    ports:
      - "8080:8000"
    volumes:
      - ./ml-engine:/app
    environment:
      - ENV=development
      
  # frontend:
  #     build:
  #       context: ./frontend
  #       dockerfile: Dockerfile
  #     container_name: coopflow_frontend
  #     ports:
  #       - "3000:3000"
  #     volumes:
  #       - ./frontend:/app
  #       - /app/node_modules
  #     environment:
  #       - NODE_ENV=development
  #       - PORT=3000
  #       - HOSTNAME=0.0.0.0  
  #       - WATCHPACK_POLLING=true 
  #       - CHOKIDAR_USEPOLLING=true
  #     command: tail -f /dev/null 


  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: coopflow_frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - PORT=3000
      - HOSTNAME=0.0.0.0  
      - WATCHPACK_POLLING=true 
      - CHOKIDAR_USEPOLLING=true
    command: npm run dev  

volumes:
  pgdata: